from fpdf import FPDF
import csv
import os
from typing import Dict
from datetime import datetime


class ReportService:
    def __init__(self):
        self.reports_dir = "reports"
        os.makedirs(self.reports_dir, exist_ok=True)

    async def generate_pdf_report(self, test_type: str, test_data: Dict) -> str:
        try:
            pdf = FPDF()
            pdf.add_page()
            pdf.set_font("Arial", "B", 16)

            pdf.cell(0, 10, f"Learning Disability Detection Report", ln=True, align="C")
            pdf.set_font("Arial", "", 12)
            pdf.ln(5)

            pdf.cell(0, 10, f"Test Type: {test_type.capitalize()}", ln=True)
            pdf.cell(0, 10, f"Date: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
            pdf.ln(5)

            pdf.set_font("Arial", "B", 14)
            pdf.cell(0, 10, "Test Results", ln=True)
            pdf.set_font("Arial", "", 12)

            prediction_class = test_data.get("prediction_class", "Unknown")
            confidence = test_data.get("confidence_score", 0.0)

            pdf.cell(0, 10, f"Prediction: {prediction_class}", ln=True)
            pdf.cell(0, 10, f"Confidence Score: {confidence:.2%}", ln=True)
            pdf.ln(5)

            if test_type == "dysgraphia":
                pdf.set_font("Arial", "B", 14)
                pdf.cell(0, 10, "Analysis Details", ln=True)
                pdf.set_font("Arial", "", 12)
                pdf.cell(0, 10, f"Model Version: {test_data.get('model_version', 'N/A')}", ln=True)

            elif test_type == "dyscalculia":
                pdf.set_font("Arial", "B", 14)
                pdf.cell(0, 10, "Quiz Statistics", ln=True)
                pdf.set_font("Arial", "", 12)

                quiz_stats = test_data.get("quiz_responses", {})
                if isinstance(quiz_stats, list):
                    pdf.cell(0, 10, f"Total Questions: {len(quiz_stats)}", ln=True)

            pdf.ln(10)
            pdf.set_font("Arial", "I", 10)
            pdf.multi_cell(0, 5,
                "Note: This report is generated by an AI system and should be reviewed by a qualified professional. "
                "It is intended for screening purposes only and not as a definitive diagnosis."
            )

            filename = f"{test_type}_report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
            filepath = os.path.join(self.reports_dir, filename)
            pdf.output(filepath)

            return filepath

        except Exception as e:
            print(f"Error generating PDF report: {e}")
            raise

    async def generate_csv_report(self, test_type: str, test_data: Dict) -> str:
        try:
            filename = f"{test_type}_report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.csv"
            filepath = os.path.join(self.reports_dir, filename)

            with open(filepath, 'w', newline='') as csvfile:
                writer = csv.writer(csvfile)

                writer.writerow(["Learning Disability Detection Report"])
                writer.writerow(["Test Type", test_type.capitalize()])
                writer.writerow(["Date", datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')])
                writer.writerow([])

                writer.writerow(["Metric", "Value"])
                writer.writerow(["Prediction Class", test_data.get("prediction_class", "Unknown")])
                writer.writerow(["Confidence Score", f"{test_data.get('confidence_score', 0.0):.4f}"])
                writer.writerow(["Model Version", test_data.get("model_version", "N/A")])
                writer.writerow([])

                if test_type == "dyscalculia" and "quiz_responses" in test_data:
                    writer.writerow(["Quiz Details"])
                    writer.writerow(["Question", "Answer", "Correct", "Time Taken"])

                    quiz_responses = test_data.get("quiz_responses", [])
                    if isinstance(quiz_responses, list):
                        for idx, response in enumerate(quiz_responses):
                            writer.writerow([
                                idx + 1,
                                response.get("answer", "N/A"),
                                "Yes" if response.get("is_correct") else "No",
                                f"{response.get('time_taken', 0)}s",
                                response.get("score", 0)
                            ])

            return filepath

        except Exception as e:
            print(f"Error generating CSV report: {e}")
            raise
